### PR TITLE
Update grunt-sass within package.json.

### LINKED ISSUE #51: Update to Libsass 3.2.4 (includes @at-root)
This will require updating grunt-sass

### PR DESCRIPTION
**Pull request by mherchel**
Resolves #51

### CODE REVIEW

**Comment by mherchel** [comment]
This is ready

**Comment by krisbulman** [comment]
@mherchel merge conflict

**Comment by mdrummond** [comment]
This should resolve the merge conflict.

**Comment by carwin** [comment]
I trumped this with #73 mainly because I didn't see it before.

**Pull request closed without merging**
