### PR TITLE
#3 Remove core CSS files

### PR DESCRIPTION
**Pull request by justafish**

### CODE REVIEW

**Comment by krisbulman** [comment]
This is a super lame bug, removing CSS files like this is the accepted (and even recommended) practice.  [simpleagg](https://www.drupal.org/project/simple_aggregation) actually fixes this, but we can't expect that to be the default on any project. 

 From simple aggregation module
> Prevents empty aggregate files from being loaded.

**Comment by carwin** [comment]
It might be ugly, but like you said we can't assume we have `simpleagg` or `advagg` on every project. 

Personally, I'd rather have a better final product out of the box and deal with some ugly `unset`s. Does anyone else want to weight in?

**Comment by krisbulman** [comment]
@carwin we should actually be carrying this convo on in the main thread, oops

**Comment by krisbulman** [comment]
Closing this for now, i will research and make a new PR

**Pull request closed without merging**
