### PR TITLE
adds sass-globbing for the base folder

### PR DESCRIPTION
**Pull request by fender**
Adding new files to the `base` folder wasn't doing anything. I've added it to the `sass-globbing` task to fix that.

### CODE REVIEW

**Comment by carwin** [comment]
I think this might be because we're still a bit up in the air on the usefulness of the base directory. It's nice in theory, but it always seems like the most unused part of our organizational system.

Does anyone have any thoughts around this?

**Comment by fender** [comment]
I did get a bit confused about whether to place some files in `base` or `component`. Take `_button.scss` for example. It's a base file because `button` is a 'base' HTML element but I also wanted the same style to apply for elements with class `.button`. So would I also then have to make a `_button.scss` in `component` and extend the base styles?

**Comment by krisbulman** [comment]
After working with React, which relies heavily on a component mindset, I still see a use for base styles. For one, if you are not modifying normalize.scss (including it externally), it's a place to set some basic resets in _root.scss like box-sizing, font-size on html, body/html height hacks, etc. It's also a good place to add _fonts.scss for your web font declarations, base animation keyframes, and set up your root typography stuff. 

I find it's important to keep it clear of component related stuff, your components should be standalone. However I break this rule sometimes, and often set-up _links.scss here, for base link styling.

base-examples

**Comment by krisbulman** [comment]
I don't recommend setting up globbing here at all though. _root and _font declarations specifically need to be prioritized.

**Comment by carwin** [comment]
Well, this has been open long enough for people to say what they will about this. I'm in agreement with @krisbulman. If we keep the base directory, it should be for things we prioritize, not glob.

**Pull request closed without merging**
